import { defineConfig } from "@playwright/test";

export default defineConfig({
  testDir: "./e2e",
  timeout: 60_000,
  workers: 1,
  use: {
    baseURL: "http://localhost:8081",
    headless: true,
    screenshot: "only-on-failure",
  },
  webServer: {
    command: "npx serve apps/app/dist -p 8081 -s",
    port: 8081,
    timeout: 10_000,
    reuseExistingServer: true,
  },
  projects: [
    {
      name: "ci",
      retries: 0,
      testMatch: [
        "app-web.spec.ts",
        "app-settings.spec.ts",
        "app-keyboard-nav.spec.ts",
        "app-modal-escape.spec.ts",
        "app-chat-enter.spec.ts",
        "app-daemons-empty.spec.ts",
        "app-session-disconnect-banner.spec.ts",
        "app-pairing-a11y.spec.ts",
        "app-pairing-scan-web.spec.ts",
        "app-font-picker-a11y.spec.ts",
        "app-aria-disabled.spec.ts",
        "app-modal-dialog-aria.spec.ts",
        "app-tablist-aria.spec.ts",
        "app-voice-button-aria.spec.ts",
        "app-listitem-aria.spec.ts",
        "app-session-back-nav.spec.ts",
        "app-settings-updates-aria.spec.ts",
        "app-chat-send-unpaired.spec.ts",
        "app-pairing-scan-back-nav.spec.ts",
        "app-aria-level.spec.ts",
        "app-modal-inert-bg.spec.ts",
        "app-testid-stability.spec.ts",
        "app-sessions-empty-tab-order.spec.ts",
        "app-diagnostics-a11y.spec.ts",
        "app-input-autocomplete.spec.ts",
        "app-api-key-modal.spec.ts",
        "app-modal-focus-trap-disabled.spec.ts",
        "app-toast-live-region.spec.ts",
        "app-settings-heading-levels.spec.ts",
        "app-chat-send-tab-reachable.spec.ts",
        "app-pairing-connect-tab-reachable.spec.ts",
        "app-text-tertiary-contrast.spec.ts",
        "app-theme-persistence.spec.ts",
        "app-pairing-input-hint.spec.ts",
        "app-font-picker-keyboard.spec.ts",
        "app-reduced-motion.spec.ts",
        "app-chat-ime-composition.spec.ts",
        "app-api-key-save-tab-reachable.spec.ts",
        "app-font-size-boundary-tab-reachable.spec.ts",
        "app-diagnostics-heading-hierarchy.spec.ts",
        "app-chat-input-autogrow.spec.ts",
        "app-terminal-tab-escape.spec.ts",
        "app-session-initial-focus.spec.ts",
        "app-daemon-card-a11y.spec.ts",
        "app-rename-modal-tab-reachable.spec.ts",
        "app-session-tabpanel-aria.spec.ts",
        "app-font-picker-initial-focus.spec.ts",
        "app-pairing-input-hint-live-region.spec.ts",
        "app-session-reconnect-announce.spec.ts",
        "app-session-tabs-apg.spec.ts",
        "app-tabbar-aria-label.spec.ts",
        "app-pairing-textarea-describedby.spec.ts",
        "app-font-size-announce.spec.ts",
        "app-theme-toggle-announce.spec.ts",
        "app-diagnostics-selftest-announce.spec.ts",
        "app-session-chat-log-role.spec.ts",
        "app-session-header-role.spec.ts",
        "app-input-aria-description.spec.ts",
        "app-settings-info-row-role.spec.ts",
        "app-diagnostics-rtt-announce.spec.ts",
        "app-font-picker-listbox-ownership.spec.ts",
        "app-sessions-list-ownership.spec.ts",
        "app-connection-live-region-atomic.spec.ts",
        "app-pairing-error-alert.spec.ts",
        "app-session-tabs-space-activate.spec.ts",
        "app-voice-switch-space-toggle.spec.ts",
        "app-session-tabs-roving-tabindex.spec.ts",
        "app-tabbar-roving-tabindex.spec.ts",
        "app-font-size-content-announce.spec.ts",
        "app-voice-state-live-region-mount.spec.ts",
        "app-session-stopped-banner-mount.spec.ts",
        "app-confirm-unpair-describedby.spec.ts",
        "app-rename-modal-aria-description.spec.ts",
        "app-font-picker-aria-selected-follows-focus.spec.ts",
        "app-tabbar-arrow-nav.spec.ts",
        "app-session-tabpanel-hidden.spec.ts",
        "app-font-picker-space-activates.spec.ts",
        "app-modal-trigger-haspopup.spec.ts",
        "app-tablist-aria-label.spec.ts",
        "app-input-aria-required.spec.ts",
        "app-tablist-aria-owns.spec.ts",
        "app-chat-list-ownership.spec.ts",
        "app-main-landmark.spec.ts",
        "app-diagnostics-main-landmark.spec.ts",
        "app-tabbar-navigation-landmark.spec.ts",
        "app-tablist-aria-orientation.spec.ts",
        "app-document-title.spec.ts",
        "app-pairing-aria-invalid.spec.ts",
        "app-pairing-main-landmark.spec.ts",
        "app-diagnostics-aria-expanded.spec.ts",
        "app-theme-announce-atomic.spec.ts",
        "app-chat-card-alert-no-polite.spec.ts",
        "app-voice-live-region-atomic.spec.ts",
        "app-diagnostics-aria-controls.spec.ts",
        "app-diagnostics-live-region-atomic.spec.ts",
        "app-pairing-loading-announce.spec.ts",
        "app-session-main-landmark.spec.ts",
        "app-empty-state-emoji-aria-hidden.spec.ts",
        "app-chat-log-aria-label.spec.ts",
        "app-modal-aria-labelledby.spec.ts",
        "app-font-size-spinbutton.spec.ts",
        "app-font-size-spinbutton-keyboard.spec.ts",
        "app-tabbar-aria-controls.spec.ts",
        "app-sessions-search-aria-controls.spec.ts",
        "app-pairing-aria-errormessage.spec.ts",
        "app-rename-modal-dialog-describedby.spec.ts",
        "app-daemons-list-ownership.spec.ts",
        "app-permission-card-alert-atomic.spec.ts",
        "app-chat-bubble-role.spec.ts",
        "app-add-daemon-haspopup.spec.ts",
        "app-chat-markdown-list-role.spec.ts",
        "app-tool-card-role.spec.ts",
        "app-streaming-card-aria-atomic.spec.ts",
        "app-font-size-initial-focus.spec.ts",
        "app-chat-bubble-keyboard-copy.spec.ts",
        "app-sessions-search-landmark.spec.ts",
        "app-chat-link-aria-label.spec.ts",
        "app-voice-live-region-role-status.spec.ts",
        "app-session-row-aria-current.spec.ts",
        "app-api-key-modal-describedby.spec.ts",
        "app-chat-bubble-space-activate.spec.ts",
        "app-tool-card-decorative-aria-hidden.spec.ts",
        "app-pairing-input-hint-aria-atomic.spec.ts",
        "app-system-card-decorative-aria-hidden.spec.ts",
        "app-toast-dismiss-glyph-aria-hidden.spec.ts",
        "app-chat-log-aria-live.spec.ts",
      ],
    },
    {
      name: "local",
      retries: 1,
      testMatch: ["*.spec.ts"],
    },
  ],
});
