import { expect, test } from "@playwright/test";

test.use({ viewport: { width: 1280, height: 800 } });

// Regression: RN Web's `createDOMProps` does NOT map
// `accessibilityHint` to any ARIA attribute — the prop silently drops
// on the way to the DOM. Without an explicit web spread a screen
// reader on web never hears the hint, even though native iOS/Android
// AT picks it up via `accessibilityHint`. Mirror the hint as
// `aria-description` (ARIA 1.3) on each critical text input so SR
// users on web get the same context as native.
test.describe("Critical text inputs expose aria-description on web", () => {
  test("pairing textarea has aria-description matching its hint", async ({
    page,
  }) => {
    await page.goto("/pairing");
    await page.waitForLoadState("networkidle");

    const textarea = page.getByTestId("pairing-input");
    await expect(textarea).toHaveAttribute(
      "aria-description",
      "Paste the pairing string generated by tp pair",
    );
  });

  test("API key modal input has aria-description matching its hint", async ({
    page,
  }) => {
    await page.goto("/settings");
    await page.waitForLoadState("networkidle");

    // The API Key row opens the ApiKeyModal — there's a row whose label
    // contains "API Key" / "OpenAI" depending on whether it's set. Open
    // the modal so the input mounts.
    const apiKeyRow = page.getByRole("button", { name: /API Key/i }).first();
    await apiKeyRow.click();

    // The input is the only password-type field inside the modal.
    const input = page.locator('input[type="password"]');
    await expect(input).toBeVisible();
    await expect(input).toHaveAttribute(
      "aria-description",
      "Enter your OpenAI API key for voice input",
    );
  });
});
