import { decodePairingData } from "@teleprompter/protocol/client";
import { useLocalSearchParams, useRouter } from "expo-router";
import { useEffect, useMemo, useRef, useState } from "react";
import {
  ActivityIndicator,
  Platform,
  Pressable,
  Text,
  TextInput,
  View,
} from "react-native";
import { ariaLevel, getPlatformProps } from "../../src/lib/get-platform-props";
import { usePairingStore } from "../../src/stores/pairing-store";
import { useThemeStore } from "../../src/stores/theme-store";

// Mirrors `--tp-text-tertiary` / `--tp-text-secondary` in global.css.
// TextInput.placeholderTextColor and ActivityIndicator.color expect
// literals — CSS variables only resolve on web; native silently falls
// back to the platform default, leaving these surfaces unreadable.
const PLACEHOLDER_LIGHT = "#a1a1aa";
const PLACEHOLDER_DARK = "#71717a";
const INDICATOR_LIGHT = "#71717a";
const INDICATOR_DARK = "#a1a1aa";

export default function PairingScreen() {
  const router = useRouter();
  const params = useLocalSearchParams<{ pairingData?: string }>();
  const { state, error, processScan } = usePairingStore();
  const [manualInput, setManualInput] = useState(params.pairingData ?? "");
  const pp = getPlatformProps();
  const isDark = useThemeStore((s) => s.isDark);
  const placeholderColor = isDark ? PLACEHOLDER_DARK : PLACEHOLDER_LIGHT;
  const indicatorColor = isDark ? INDICATOR_DARK : INDICATOR_LIGHT;
  const canSubmit = manualInput.trim().length > 0;
  const connectRef = useRef<View>(null);
  const inputRef = useRef<TextInput>(null);

  // Mirror disabled state to aria-disabled on the Connect button. RN
  // Web's Pressable only emits aria-disabled when the native `disabled`
  // prop is also set, but native `disabled` removes the button from the
  // browser's Tab order — a keyboard-only user would Tab past the
  // textarea straight to <body>. Same pattern as the chat Send button.
  useEffect(() => {
    if (Platform.OS !== "web") return;
    const el = connectRef.current as unknown as HTMLElement | null;
    if (!el) return;
    if (!canSubmit) el.setAttribute("aria-disabled", "true");
    else el.removeAttribute("aria-disabled");
  }, [canSubmit]);

  // RN Web's createDOMProps does not whitelist `aria-description`, so
  // any prop-level spread is silently dropped on the way to the DOM.
  // `accessibilityHint` is dropped for the same reason. Set the
  // attribute imperatively so screen readers on web get the same
  // textarea hint that native AT picks up from accessibilityHint.
  useEffect(() => {
    if (Platform.OS !== "web") return;
    const el = inputRef.current as unknown as HTMLElement | null;
    if (!el) return;
    el.setAttribute(
      "aria-description",
      "Paste the pairing string generated by tp pair",
    );
  }, []);

  // Preview the daemon being requested when arriving via deep link, so the
  // user has to explicitly confirm rather than be paired automatically.
  // Label is no longer in the QR — the daemon broadcasts it during relay
  // key exchange — so the preview shows the daemon ID until kx completes.
  const preview = useMemo(() => {
    const text = manualInput.trim();
    if (!text) return null;
    try {
      const data = decodePairingData(text);
      return {
        did: data.did,
        relay: data.relay,
      };
    } catch {
      return null;
    }
  }, [manualInput]);

  // Same gate as the inline hint View below. We hoist it so the TextInput
  // can mirror it into `aria-describedby` — wiring the hint to the input
  // gives a screen reader the link from the focused textarea to the
  // contextual validation message instead of leaving them orphaned.
  const showInputHint = manualInput.trim().length > 0 && !preview && !error;

  // Sync incoming deep-link payload into the input on mount/update.
  // We intentionally do not depend on manualInput — only react to the param.
  // biome-ignore lint/correctness/useExhaustiveDependencies: see comment above
  useEffect(() => {
    if (params.pairingData && params.pairingData !== manualInput) {
      setManualInput(params.pairingData);
    }
  }, [params.pairingData]);

  const handlePaste = async () => {
    const text = manualInput.trim();
    if (!text) return;
    await processScan(text);
    if (usePairingStore.getState().state === "paired") {
      router.replace("/");
    }
  };

  if (state === "pairing") {
    return (
      <View className="flex-1 bg-tp-bg items-center justify-center">
        <ActivityIndicator size="large" color={indicatorColor} />
        <Text className="text-tp-text-secondary mt-4">
          Processing pairing data...
        </Text>
      </View>
    );
  }

  const buttonLabel = preview ? "Confirm pairing" : "Connect";

  return (
    <View className="flex-1 bg-tp-bg pt-20 items-center">
      <View className="w-full max-w-2xl px-6">
        <Text
          accessibilityRole="header"
          {...ariaLevel(1)}
          className="text-tp-text-primary text-2xl font-bold text-center"
        >
          Pair with Daemon
        </Text>
        <Text className="text-tp-text-secondary text-center mt-2 mb-8">
          Scan the QR code shown by your daemon, or paste the pairing data
          below.
        </Text>

        {error && (
          // role="alert" already implies aria-live="assertive" + aria-atomic="true"
          // per ARIA 1.2 §6.3.3. Adding an explicit aria-live="polite" here would
          // override the implicit assertive value (per ARIA 1.2 §6.2.1) and downgrade
          // a blocking validation error to a polite announcement that NVDA/JAWS/VoiceOver
          // queue behind in-flight speech. Same fix InAppToast and UpdateBanner already
          // adopted — we just missed this banner the first time around.
          <View
            testID="pairing-error"
            nativeID="pairing-error"
            role="alert"
            className="bg-tp-error/20 border border-tp-error rounded-lg px-4 py-3 mb-4"
          >
            <Text className="text-tp-error text-sm">{error}</Text>
          </View>
        )}

        {/* Manual paste input (works on all platforms) */}
        <Text className="text-tp-text-secondary text-sm mb-2">
          Paste pairing data:
        </Text>
        <TextInput
          ref={inputRef}
          testID="pairing-input"
          className={`bg-tp-bg-input text-tp-text-primary rounded-lg px-4 py-3 font-mono text-xs mb-4 ${pp.className}`}
          placeholder="tp://p?d=..."
          placeholderTextColor={placeholderColor}
          value={manualInput}
          onChangeText={setManualInput}
          multiline
          numberOfLines={4}
          autoCapitalize="none"
          autoCorrect={false}
          // Pairing tokens are one-time bundles; leaving autoComplete on lets
          // the browser stash them in the textarea history dropdown where
          // they leak to the next user of the device.
          autoComplete="off"
          style={{ minHeight: 100, textAlignVertical: "top" }}
          accessibilityLabel="Pairing data"
          accessibilityHint="Paste the pairing string generated by tp pair"
          tabIndex={pp.tabIndex}
          // Wire the input to whichever supporting region is currently on
          // screen — the alert when there's an async error, or the inline
          // hint when the user typed something we can't decode. RN Web
          // emits aria-invalid only from a direct prop, and aria-describedby
          // has no RN equivalent, so spread on web only.
          {...(Platform.OS === "web" && error
            ? {
                "aria-invalid": true,
                "aria-describedby": "pairing-error",
              }
            : Platform.OS === "web" && showInputHint
              ? { "aria-describedby": "pairing-input-hint" }
              : {})}
        />

        {/* Inline validation hint: non-empty input that can't be decoded.
            Surfaces feedback while typing instead of waiting for the user
            to click Connect and get an after-the-fact error toast. Hidden
            when an async `error` is already on screen to avoid stacking.

            Wrap in a polite live region so a screen reader announces the
            validation feedback as it appears — without this the hint is
            invisible to SR users and they only learn the input is invalid
            after pressing Connect and hitting the after-the-fact error.
            role=status (assertive=false, polite) is the right intensity
            here: the user is still typing, so this is informational, not
            an interruption. RN's accessibilityRole union excludes
            "status", so spread role on web only; native gets the
            accessibilityLiveRegion + accessibilityRole="text" combo. */}
        {showInputHint && (
          <View
            testID="pairing-input-hint"
            nativeID="pairing-input-hint"
            accessibilityLiveRegion="polite"
            {...(Platform.OS === "web"
              ? { role: "status", id: "pairing-input-hint" }
              : {})}
            className="mb-4"
          >
            <Text className="text-tp-text-tertiary text-xs">
              Doesn't look like pairing data — should start with{" "}
              <Text className="font-mono">tp://p?d=</Text>
            </Text>
          </View>
        )}

        {preview && (
          <View className="bg-tp-bg-elevated border border-tp-border rounded-lg px-4 py-3 mb-4">
            <Text className="text-tp-text-tertiary text-xs uppercase mb-1">
              Pairing with
            </Text>
            <Text className="text-tp-text-primary text-base font-semibold font-mono">
              {preview.did}
            </Text>
            <Text className="text-tp-text-tertiary text-xs mt-1">
              via {preview.relay.replace(/^wss:\/\//, "")}
            </Text>
          </View>
        )}

        <Pressable
          testID="pairing-connect"
          ref={connectRef}
          // Drop the native `disabled` prop so the browser keeps the
          // button in Tab order (see ref useEffect above for the
          // aria-disabled mirror). Guard the press handler instead.
          onPress={() => {
            if (!canSubmit) return;
            handlePaste();
          }}
          accessibilityRole="button"
          accessibilityLabel={buttonLabel}
          accessibilityState={{ disabled: !canSubmit }}
          className={`bg-tp-accent rounded-lg py-3 items-center ${pp.className}`}
          tabIndex={pp.tabIndex}
          style={{ opacity: canSubmit ? 1 : 0.4 }}
        >
          <Text className="text-tp-text-on-color font-bold">{buttonLabel}</Text>
        </Pressable>

        {Platform.OS !== "web" && (
          <>
            <View className="flex-row items-center my-6">
              <View className="flex-1 h-px bg-tp-border" />
              <Text className="text-tp-text-tertiary mx-3">or</Text>
              <View className="flex-1 h-px bg-tp-border" />
            </View>

            <Pressable
              onPress={() => router.push("/pairing/scan")}
              accessibilityRole="button"
              accessibilityLabel="Scan QR Code"
              className={`border border-tp-border rounded-lg py-3 items-center ${pp.className}`}
              tabIndex={pp.tabIndex}
            >
              <Text className="text-tp-text-primary">Scan QR Code</Text>
            </Pressable>
          </>
        )}
      </View>
    </View>
  );
}
